### PR TITLE
[image_view] Get correct fps in video_recorder.cpp

### LINKED ISSUE #207: Incorrect frame rate of video_recorder when ~fps is different from image topic fps
Maybe same issue as http://answers.opencv.org/question/16522/video-recording-is-too-fast/ .

```
% date; rosrun image_view video_recorder image:=/left_hand_camera/depth/image _fps:=2 _codec:=M4S2; date
Fri Jul  8 23:09:57 JST 2016
[ INFO] [1467986998.561554834]: Waiting for topic /left_hand_camera/depth/image...
[ INFO] [1467986998.717792545]: Starting to record M4S2 video at [640 x 480]@2fps. Press Ctrl+C to stop recording.
^CINFO] [1467987000.446922743]: Recording frame 51
Video saved as output.avi
Fri Jul  8 23:10:00 JST 2016
```

### PR DESCRIPTION
**Pull request by wkentaro**
Close #207 

```
% date; rosrun image_view video_recorder image:=/left_hand_camera/depth/image _fps:=1; date
Fri Jul  8 23:16:32 JST 2016
[ INFO] [1467987393.530164658]: Waiting for topic /left_hand_camera/depth/image...
[ INFO] [1467987393.675201947]: Starting to record MJPG video at [640 x 480]@1fps. Press Ctrl+C to stop recording.
^CINFO] [1467987398.580576018]: Recording frame 5
Video saved as output.avi
Fri Jul  8 23:16:39 JST 2016
```

### CODE REVIEW

File: image_view/src/nodes/video_recorder.cpp [hunk 1]
```diff
@@ -70,13 +71,20 @@ void callback(const sensor_msgs::ImageConstPtr& image_msg, const sensor_msgs::Ca
     }
     else if (outputVideo.isOpened() && info) return;
 
+    if ((g_last_wrote_time != ros::Time(0)) && ((ros::Time::now() - g_last_wrote_time) < ros::Duration(1 / fps)))
```
Comment (vrabaud) [inline image_view/src/nodes/video_recorder.cpp]: instead of ros::Time::now(), you should use image_msg->header.stamp

The first condition is probably useless right ?

Comment (wkentaro) [inline image_view/src/nodes/video_recorder.cpp]: Updated.

**Comment by wkentaro** [comment]
Fixed.

**Comment by vrabaud** [comment]
thx !
